name: Build Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Сборка Release APK
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: '33.0.2'
          ndk-version: '25.2.9519653'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew clean :app:assembleRelease --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: NeuroAI-Offline-APK
          path: app/build/outputs/apk/release/NeuroAI-Offline-release.apk
