name: Build Debug and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./app/gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: ./app

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: ./app

      - name: Debug all .apk paths
        run: find ./app -name "*.apk"

      - name: List APK files
        run: |
          echo "== Debug APKs =="
