name: Build Debug and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: List all APKs
        run: |
          echo "== APKs in Debug =="
          ls -alh app/build/outputs/apk/debug || echo "Debug folder not found"
          echo "== APKs in Release =="
          ls -alh app/build/outputs/apk/release || echo "Release folder not found"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-release-apk
          path: app/build/outputs/apk/release/app-release.apk
