name: Build Debug and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./app/gradlew

      - name: Build Debug APK
        working-directory: ./app
        run: ./gradlew assembleDebug

      - name: Build Release APK
        working-directory: ./app
        run: ./gradlew assembleRelease

      - name: Debug all .apk paths
        run: find app/ -name "*.apk"

      - name: List APK files
        run: |
          echo "== Debug APKs =="
          ls -alh app/app/build/outputs/apk/debug || echo "No debug APK found"
          echo "== Release APKs =="
          ls -alh app/app/build/outputs/apk/release || echo "No release APK found"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-debug-apk
          path: app/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-release-apk
          path: app/app/build/outputs/apk/release/app-release.apk
