name: Build Debug and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: Find all APKs recursively
        run: find . -type f -name "*.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-debug-apk
          path: "**/app-debug.apk"

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: neuroai-release-apk
          path: "**/app-release.apk"
