name: Decode gradle-wrapper.jar

on:
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode base64 to gradle-wrapper.jar
        run: |
          base64 -d app/gradle/wrapper/gradle-wrapper.jar.base64 > app/gradle/wrapper/gradle-wrapper.jar
