name: Decode gradle-wrapper.jar

on:
  push:
    paths:
      - 'app/gradle/wrapper/gradle-wrapper.jar.base64'

jobs:
  decode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Decode base64 into gradle-wrapper.jar
        run: |
          base64 -d app/gradle/wrapper/gradle-wrapper.jar.base64 > app/gradle/wrapper/gradle-wrapper.jar

      - name: Commit decoded .jar
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add app/gradle/wrapper/gradle-wrapper.jar
          git commit -m 'Decoded gradle-wrapper.jar from base64'
          git push
